---
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart clamav
  service:
    name: clamav-daemon
    state: restarted

- name: restart auditd
  service:
    name: auditd
    state: restarted