---
- name: Install Node.js dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm
  when: ansible_os_family == "Debian"

- name: Create application directory
  file:
    path: /opt/vitatrackapp
    state: directory
    owner: vitatrack
    group: vitatrack
    mode: '0755'

- name: Create application logs directory
  file:
    path: /var/log/vitatrackapp
    state: directory
    owner: vitatrack
    group: vitatrack
    mode: '0755'

- name: Create application environment file
  template:
    src: env.j2
    dest: /opt/vitatrackapp/.env
    owner: vitatrack
    group: vitatrack
    mode: '0600'

- name: Create application service file
  template:
    src: vitatrackapp.service.j2
    dest: /etc/systemd/system/vitatrackapp.service
    owner: root
    group: root
    mode: '0644'
  notify: restart vitatrackapp

- name: Ensure application service is enabled
  service:
    name: vitatrackapp
    enabled: yes