apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vitatrack-admin
  namespace: vitatrack  # Specify your application namespace
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: [""]
    resources: ["pods/log", "pods/status"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vitatrack-admin-binding
  namespace: vitatrack  # Same namespace as the Role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vitatrack-admin
subjects:
  - kind: User
    name: admin
    apiGroup: rbac.authorization.k8s.io