replicaCount: 2
image:
  repository: vitatrack/frontend
  tag: latest
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80
service:
  type: ClusterIP
  port: 80 