---
- name: Download Helm
  get_url:
    url: https://get.helm.sh/helm-v3.10.0-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
    mode: '0644'

- name: Create Helm directory
  file:
    path: /tmp/helm
    state: directory
    mode: '0755'

- name: Extract Helm
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/helm
    remote_src: yes

- name: Move Helm binary
  copy:
    src: /tmp/helm/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    remote_src: yes

- name: Clean up Helm installation files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/helm
    - /tmp/helm.tar.gz