---
- name: Set default UFW policies
  ufw:
    state: enabled
    policy: deny
    direction: "{{ item }}"
  loop:
    - incoming
    - outgoing
    - routed

- name: Allow SSH connections
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Allow HTTP connections
  ufw:
    rule: allow
    port: http
    proto: tcp
  when: server_type == 'web'

- name: Allow HTTPS connections
  ufw:
    rule: allow
    port: https
    proto: tcp
  when: server_type == 'web'

- name: Allow internal network traffic
  ufw:
    rule: allow
    src: 10.0.0.0/8

- name: Enable UFW logging
  ufw:
    logging: on