---
- name: Download CloudWatch agent
  get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: /tmp/amazon-cloudwatch-agent.deb
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Install CloudWatch agent
  apt:
    deb: /tmp/amazon-cloudwatch-agent.deb
  when: ansible_os_family == "Debian"

- name: Configure CloudWatch agent
  template:
    src: cloudwatch-config.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: '0644'
  notify: restart cloudwatch-agent

- name: Ensure CloudWatch agent service is enabled and running
  service:
    name: amazon-cloudwatch-agent
    state: started
    enabled: yes