---
- name: Download Prometheus Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Create Node Exporter directory
  file:
    path: /tmp/node_exporter
    state: directory
    mode: '0755'

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/node_exporter
    remote_src: yes

- name: Move Node Exporter binary
  copy:
    src: /tmp/node_exporter/node_exporter-1.5.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'
    remote_src: yes

- name: Create Node Exporter user
  user:
    name: node_exporter
    shell: /bin/false
    system: yes
    create_home: no

- name: Create Node Exporter service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: restart node_exporter

- name: Ensure Node Exporter service is enabled and running
  service:
    name: node_exporter
    state: started
    enabled: yes

- name: Clean up Node Exporter installation files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/node_exporter
    - /tmp/node_exporter.tar.gz