---
- name: Install unattended-upgrades package
  apt:
    name: unattended-upgrades
    state: present
  when: ansible_os_family == "Debian"

- name: Configure unattended-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "Debian"
  notify: restart unattended-upgrades

- name: Configure unattended-upgrades security
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "Debian"
  notify: restart unattended-upgrades