---
- name: restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart ntp
  service:
    name: "{{ ntp_service_name }}"
    state: restarted